### PR TITLE
insertion_sort

### PR DESCRIPTION
**Pull request by jhachirag7**

### CODE REVIEW

**Comment by gay3tiwariiiii** [comment]
What is Insertion sort? Can You please explain.??

**Comment by jhachirag7** [comment]
first start with second element in array and check with previous elements and swap with the selected number if the numbers is greater than selected iterate it till the end of the element

**Comment by gay3tiwariiiii** [comment]
Can you provide us with input and output of your code?

**Comment by jhachirag7** [comment]
5
5 4 3 2 1
4 5 3 2 1
3 4 5 2 1
2 3 4 5 1
1 2 3 4 5

**Comment by gay3tiwariiiii** [comment]
Can you write the same code for reverse?

**Comment by jhachirag7** [comment]
just print array the array in backward.

**Pull request merged**
